export const createTables = [
  `CREATE TABLE IF NOT EXISTS STORES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
  );`,
  
  `CREATE TABLE IF NOT EXISTS SSTORE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    store INTEGER NOT NULL,
    FOREIGN KEY (store) REFERENCES STORES(id)
  );`,

  `CREATE TABLE IF NOT EXISTS UNIFORMS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    size TEXT NOT NULL
  );`,

  `CREATE TABLE IF NOT EXISTS OPERATIONS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    store INTEGER NOT NULL,
    type BOOLEAN NOT NULL,
    concept TEXT NOT NULL,
    uniform INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    date DATETIME NOT NULL,
    FOREIGN KEY (store) REFERENCES SSTORE(id),
    FOREIGN KEY (uniform) REFERENCES UNIFORMS(id)
  );`
];
